[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmd = "npm install --legacy-peer-deps"

[phases.build]
cmd = "echo 'No build step required'"

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NIXPACKS_NO_DEFAULT_CACHE_MOUNT = "1"

[providers.node]
version = "18"

