providers = ["node"]

[variables]
NODE_VERSION = "18"
NODE_ENV = "production"
NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmd = "rm -f package-lock.json && npm install --legacy-peer-deps"

[phases.build]
cmd = "echo 'No build step required'"

[phases.start]
cmd = "npm start"