[providers.node]
version = "18"

[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmd = "rm -f package-lock.json && npm install --legacy-peer-deps"

[phases.build]
cmd = "echo 'No build step required'"

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_LEGACY_PEER_DEPS = "true"

